### ISSUE TITLE
Intellisense doesn't seem to like the $ sign in variable names

### ISSUE THREAD

**Issue by mrupp12bit** [JohnArcher/vscode-hollywood-mal#6]
As posted here: https://forums.hollywood-mal.com/viewtopic.php?f=13&t=2424&start=10

![VSCode_Intellisense](https://user-images.githubusercontent.com/38189288/107558760-77fcd400-6bdb-11eb-9b16-d500fd8d1651.png)

**Comment by JohnArcher** [comment]
Good spot! I tried different things in the last couple of days since you reported this, but doesn't work yet. I am not sure why, though. Currently I use the textmate grammar syntax with a proper regular expression, but somehow `$` and `!` work like a delimiter here. I'll have to further investigate that.

**Comment by mrupp12bit** [comment]
It does work with JavaScript:
![image](https://user-images.githubusercontent.com/38189288/108590984-a3638980-7366-11eb-95a3-b08f1c241917.png)

Maybe this helps somehow...

**Comment by JohnArcher** [comment]
Thank you. Yeah, you see the difference between the JS and the HW screenshot: In JS the varibale `test$` is marked as that as you can see with the icon in front of the intellisense popup. In HW this string is just a dictionary entry (see the "abc" icon). Still not sure how I could influence the dictionary behaviour, but the way to go will be to use the same approach as with recognizing functions (see your other issue).
